[build-system]
requires = ["setuptools >= 61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymorph"
version = "0.8.0"
requires-python = ">=3.12.10"
dependencies = [
  "numpy>=2.2.5", 
  "matplotlib>=3.10.0",
  "fitsio>=1.2.6"
]
authors = [
  {name = "Vinu Vikraman", email = "vvinuv@gmail.com"},
  {name = "Alan Meert"},
  {name = "Yogesh Wadadekar"},
  {name = "Ajit Kembhavi"},
  {name = "G V Vijayagovidan"},
]
maintainers = [
  {name = "Vinu Vikraman", email = "vvinuv@gmail.com"}
]
description = "Pipeline for Morphological two dimensional decomposition and non-parametric methods"
readme = "README.rst"
#license = "GPL"
#license-files = ["LICENSE"]
keywords = ["morphology", "pymorph", "decomposition"]
classifiers = [
  #"Development Status :: 4 - Beta",
  #"Programming Language :: Python"
]

[project.optional-dependencies]
db = [
  "sqlite3>=3.51.2",
  "scipy>=1.15.3"
]

[project.urls]
Homepage = "https://github.com/vvinuv/pymorph"
Repository = "https://github.com/vvinuv/pymorph"

[project.scripts]
pymorph_bin = "pymorph.pymorph:pymorph"

[tool.setuptools.packages.find]
where = ["src"]
