#!/usr/bin/env python
import sys
import pymorph

def parse_args():
    """Handle the command line arguments to corr2 executable.
    """
    import argparse

    version_str = "PyMorph version"
    description = "Efficient code for computing 2-point correlation functions.\n"

    parser = argparse.ArgumentParser(description=description, 
                                     add_help=True, epilog=version_str)
    parser.add_argument('config_file', type=str, nargs='?',
                        help='the configuration file')
    parser.add_argument('variables', type=str, nargs='*',
                        help='Additional the config file. ')

    args = parser.parse_args()


    return args


def main():
    args = parse_args()

    # Read the config file
    p = pymorph.PyMorph()
    p.set_sexparams()
    p.pymorph()

if __name__ == '__main__':
    main()

