#!/usr/bin/env python
import sys
import pymorph

def get_args():
    """Handle the command line arguments
    """

    name = f'PyMorph {pymorph.version}'
    description = "2D dimensional decomposition of galaxy image"
    
    print(f'{name}: {description}')



def main():
    args = get_args()
 

    p = pymorph.PyMorph()
    #p.set_sexparams()
    p.pymorph()

if __name__ == '__main__':
    main()

