;Configure file for PyMorph. Authors: Vinu Vikram, Yogesh Wadadekar and Ajit Kembhavi (IUCAA), G V Vijayagovidan 2008, Alan Meert (UPenn)

[imagecata]
;Specify the input images and Catalogues
imagefile = frame-r-003919-4-0273.fits 

;The weight image. If it contains the string 'rms', this will treated as 
;RMS_MAP and if it contains weight, then that will be treated as WEIGHT_MAP. 
;If nothing found, then by default it is treated as MAP_RMS 
whtfile = frame-r-003919-4-0273_rms.fits

;catalogue of galaxies. The header information are
;GAL_ID RA DEC Z STAR or GAL_ID RA1 RA2 RA2 DEC1 DEC2 Z STAR or
;GAL_ID RA DEC Z or GAL_ID RA DEC
obj_cata = input.cat 
;The sextractor catalogue from which initial values are determined 
sex_cata = sex.cat            


;rootname is the unique value for all the input object. This will included to
;filenames of every file created by pymorph
rootname = cl1358

;The directory containing input images. It should be in the current 
;directory. If commented out, then program uses current directory
datadir = /Users/vinu/github/pymorph/examples/full_image

;The directory containing output data. If commented out, then program uses
;current directory
;DON'T change
outdir = './'

[external]
;;;----Set the SExtractor and GALFIT path here----;;;
GALFIT_PATH = /usr/local/bin/galfit
;/home/vinu/software/galfit/modified/galfit 
SEX_PATH = /opt/homebrew/bin//sex

[psf]
;Star-galaxy classification. stargal_prob is also used as the limit
;of star-galaxy classification in the fit_and_fit mode 
stargal_prob = 0.7 

;PSF image size will be startsize times the SMA given by SExtractor
star_size = 20                         

;List of psf containg their position information. psf_RA1RA2RA3+DEC1DEC2DEC3.fits. This will convert to RA and DEC and updated in the PSF header.
;If psflist=@filename, then the PSF will read from that file.
psflist = psf_1447218+0838538.fits, psf_1447219+0828392.fits, psf_1447219+0828392.fits, psf_1447263+0828251.fits, psf_1447314+0837484.fits, psf_1447278+0834215.fits, psf_1447258+0833591.fits, psf_1447248+0834458.fits, psf_1447184+0830495.fits

[mask]
;;;----Conditions for Masking----;;;
;Masking will be done for neighbours whose semimajor*threshold overlaps with 
;threshold * semi-major axis of the object and area of the neighbour 
;less than thresh_area * object area in ;sq.pixel. 
;The masking will be for a circular region of radius mask_reg*semi-major 
;axis of the nighbour with respect to the center of the neightbour.
manual_mask = 0
mask_reg = 3.0
thresh_area = 10.1
threshold = 4.5                       
           
[size]
;Size of the cut out and search conditions
;size = [resize?, imsize?, fracrad, square?, fixsize]
size_list = 1, 0, 20, 1, 120              
;The search radius in arcsec 
searchrad = 0.9                     

[cosmology]
;Parameters for calculating the physical parameters of galax
;Pixel scale (arcsec/pixel)
pixelscale = 0.25                    

[nonparams]
;Parameters to be set for calculating the CASGM. Don't change these parameters
back_extraction_radius = 15.0
;back_ini_xcntr = 32.0 
;back_ini_ycntr = 22.0
angle = 180.0

[modes]
;PyMorph fitting modes
;True if we provide cutouts
galcut = False
;This runs galfit software. Don't change
decompose = True
;detail=True then the galfit configuration will take random number of
;configuration values, magnitude, radius and Sersic index, which is
;specfied by number_random keyword. The original initial values are from
;the sextractor 
detail = True
number_random = 50

;Will run casgm 
casgm = False
;if find_and_fit = True, then maglim = [faint_mag, bright_mag]
;find_and_fit takes all the objects in that maglim and fit it in one go.
;Don't change it
find_and_fit = False

[findfit]
;It is the lower and upper magnitudes of objects if the mode is find_and_fit
maglim = 22, 15 

[mag]
;magnitude zero point and the photometric filter
mag_zero = 25.256                     
photo_filter = 'SDSS_r'

[galfit]
;Galfit Controls
;The components to be fitted to the object
components = bulge, disk, bar
;set to False to fit sersic bulge, set to true to fit devacouler's bulge (n = 4)
devauc = False 

;;;---fixing = [bulge_center, disk_center, sky, bar_center]
fitting = 1, 1, 1, 1

;Skip if bbox=-99 and barbox=-99. Otherwise these take is as the initial
;boxiness of bulge and bar if these are found in components
bbox = 0
barbox = 0


[version]
galfitv = 3.0.2
pymorphv = 0.1

[diagnosis]
;The following conditions are used to classify fit good/bad
;Consider the fit bad if the chi2nu larger than chi2nu_limit
chi2nu_limit = 0.5                          
;goodness limit is how many sigma (ie. how many significant) is classified 
;as a good chi2 for a two tailed test. 
goodness_limit = 3                       
;< abs(center - fitted center)
center_deviation_limit = 3.0                
;do_plot=True makes plotting
do_plot = False

[params_limit]
;Ncntr set the limit on center of the components, ie, +/- Ncntr
;NMag is set the limit on magnitude. It is defined as MAG_AUTO+/-NMag .
;Maximum of radius is defined as NRadius * Sectractor half light radius and
;the minimum will be set to 0.2 pix.
Ncntr = 2
NMag = 3
NRadius = 10

;Need to set lower and higher sersic index
LN = 0.2
UN = 10
UNbar = 2.2

[detail_limit]
;initial magnitude +/- delmag
delmag = 0.5
;radius will be between 0.6 * initial radius and 1.3 * initial radius 
delr = 0.6, 1.3
;Sersic index will be between 0.5 * initial Serisc and 1.5 * initial Sersic
deln = 0.5, 1.5
;initial bar magnitude +/- delmag
magbar = 0.5
;It will be frbar * radius of the bulge, is fraction of bulge radius
frbar = 1.2

[sextractor]
;To find the initial configuration parameters. Some parameters 
;such as GAIN are need to change for every telescope
SEEING_FWHM = 1 
DETECT_MINAREA = 6
DETECT_THRESH = 1.5
ANALYSIS_THRESH = 1.5
GAIN = 4.71
PHOT_FLUXFRAC = 0.8
FILTER = Y
FILTER_NAME = default.conv
DEBLEND_NTHRESH = 32
DEBLEND_MINCONT = 0.005
BACK_SIZE = 64
BACK_FILTERSIZE = 3
BACKPHOTO_TYPE = GLOBAL
BACKPHOTO_THICK = 24
WEIGHT_TYPE = MAP_RMS
